services:
    aaronadal.validator.data_provider.factory:
        class: Aaronadal\ValidatorBundle\Validator\DataProvider\DataProviderFactory

    data_provider_factory:
        alias: aaronadal.validator.data_provider.factory
        public: true

    aaronadal.validator.data_setter.factory:
        class: Aaronadal\Validator\Validator\DataSetter\DataSetterFactory

    data_setter_factory:
        alias: aaronadal.validator.data_setter.factory
        public: true

    aaronadal.validator.subject.factory:
        class: Aaronadal\ValidatorBundle\Subject\SubjectFactory
        arguments: 
            - '@data_provider_factory'
            - '@data_setter_factory'
            - '@request_stack'
            - '@session'

    subject_factory:
        alias: aaronadal.validator.subject.factory
        public: true

    aaronadal.validator.factory:
        class: Aaronadal\Validator\Validator\ValidatorFactory

    validator_factory:
        alias: aaronadal.validator.factory
        public: true
