services:
    aaronadal.validator.data_provider.factory:
        class: Aaronadal\ValidatorBundle\Validator\DataProvider\DataProviderFactory

    data_provider_factory:
        alias: aaronadal.validator.data_provider.factory
        public: true

    aaronadal.validator.data_setter.factory:
        class: Aaronadal\Validator\Validator\DataSetter\DataSetterFactory

    data_setter_factory:
        alias: aaronadal.validator.data_setter.factory
        public: true

    aaronadal.validator.subject.factory:
        class: Aaronadal\ValidatorBundle\Subject\SubjectFactory
        arguments:
            - '@data_provider_factory'
            - '@data_setter_factory'
            - '@request_stack'
            - '@session'

    subject_factory:
        alias: aaronadal.validator.subject.factory
        public: true

    aaronadal.validator.factory:
        class: Aaronadal\Validator\Validator\ValidatorFactory

    validator_factory:
        alias: aaronadal.validator.factory
        public: true

    Aaronadal\Validator\Validator\DataProvider\DataProviderFactoryInterface:
        alias: data_provider_factory

    Aaronadal\Validator\Validator\DataSetter\DataSetterFactoryInterface:
        alias: data_setter_factory

    Aaronadal\Validator\Subject\SubjectFactoryInterface:
        alias: subject_factory

    Aaronadal\Validator\Validator\ValidatorFactoryInterface:
        alias: validator_factory

    Aaronadal\ValidatorBundle\Validator\DataProvider\DataProviderFactory:
        alias: aaronadal.validator.data_provider.factory

    Aaronadal\Validator\Validator\DataSetter\DataSetterFactory:
        alias: aaronadal.validator.data_setter.factory

    Aaronadal\ValidatorBundle\Subject\SubjectFactory:
        alias: aaronadal.validator.subject.factory

    Aaronadal\Validator\Validator\ValidatorFactory:
        alias: aaronadal.validator.factory
